/**
  * CREATE SEQUENCES SECTION
  */

CREATE SEQUENCE seq_bar
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_cuenta
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_gimnasio
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_habitacion
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_internet
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_lavanderia
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_piscina
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_plan_consumo
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_prestamo_utensilios
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_producto
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_reserva
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_reserva_cliente
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_reserva_servicio
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_salon_conferencia
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_servicio
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_spa
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_supermercado
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_tienda
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_tipos_habitacion
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_usuario
START WITH 1
INCREMENT BY 1;
